#ifndef ASCII_TABLE_H
#define ASCII_TABLE_H

enum {
  ASCII_SPACE = 32,
  ASCII_EXCLAMATION,
  ASCII_DOUBLE_QUOTE,
  ASCII_HASH_SIGN,
  ASCII_DOLLAR_SIGN,
  ASCII_PERCENT_SIGN,
  ASCII_AMPERSAND,
  ASCII_SINGLE_QUOTE,
  ASCII_LEFT_PAREN,
  ASCII_RIGHT_PAREN,
  ASCII_ASTERISK,
  ASCII_PLUS_SIGN,
  ASCII_COMMA,
  ASCII_HYPHEN,
  ASCII_PERIOD,
  ASCII_SLASH,
  ASCII_0, ASCII_1, ASCII_2, ASCII_3, ASCII_4,
  ASCII_5, ASCII_6, ASCII_7, ASCII_8, ASCII_9,
  ASCII_COLON,
  ASCII_SEMICOLON,
  ASCII_LESS_THAN_SIGN,
  ASCII_EQUALS,
  ASCII_GREATER_THAN_SIGN,
  ASCII_QUESTION_MARK,
  ASCII_AT_SIGN,
  ASCII_UPPER_A, ASCII_UPPER_B, ASCII_UPPER_C, ASCII_UPPER_D, ASCII_UPPER_E,
  ASCII_UPPER_F, ASCII_UPPER_G, ASCII_UPPER_H, ASCII_UPPER_I, ASCII_UPPER_J,
  ASCII_UPPER_K, ASCII_UPPER_L, ASCII_UPPER_M, ASCII_UPPER_N, ASCII_UPPER_O,
  ASCII_UPPER_P, ASCII_UPPER_Q, ASCII_UPPER_R, ASCII_UPPER_S, ASCII_UPPER_T,
  ASCII_UPPER_U, ASCII_UPPER_V, ASCII_UPPER_W, ASCII_UPPER_X, ASCII_UPPER_Y,
  ASCII_UPPER_Z,
  ASCII_LEFT_BRACKET,
  ASCII_BACKSLASH,
  ASCII_RIGHT_BRACKET,
  ASCII_CARET,
  ASCII_UNDERSCORE,
  ACSII_GRAVE,
  ASCII_LOWER_A, ASCII_LOWER_B, ASCII_LOWER_C, ASCII_LOWER_D, ASCII_LOWER_E,
  ASCII_LOWER_F, ASCII_LOWER_G, ASCII_LOWER_H, ASCII_LOWER_I, ASCII_LOWER_J,
  ASCII_LOWER_K, ASCII_LOWER_L, ASCII_LOWER_M, ASCII_LOWER_N, ASCII_LOWER_O,
  ASCII_LOWER_P, ASCII_LOWER_Q, ASCII_LOWER_R, ASCII_LOWER_S, ASCII_LOWER_T,
  ASCII_LOWER_U, ASCII_LOWER_V, ASCII_LOWER_W, ASCII_LOWER_X, ASCII_LOWER_Y,
  ASCII_LOWER_Z,
  ASCII_LEFT_CURLYBRACE,
  ASCII_VERTICAL_BAR,
  ASCII_RIGHT_CURLYBRACE,
  ASCII_TILDE
};

enum {
  ASCII_COUNT = 128,
  EXTENDED_ASCII_COUNT = 255
};

#endif /* ASCII_TABLE_H */
