#ifndef SURFACE_H
#define SURFACE_H

#include <SDL.h>
#include "base_types.h"


enum {
  SURFACE_SCALE_PROGRESSIVE,
  SURFACE_SCALE_PROGRESSIVE2,
  SURFACE_SCALE_INTERLACED,
  SURFACE_SCALE_INTERLACED2
};

#endif /* SURFACE_H */
